---
title: Hotel Cancelations Data Dictionary
output:
  html_document:
    theme: cerulean
    css: https://rsacdn.link/teachthis/css/style.css
---

## The Hotels Data

The data comes from an open hotel booking data set from [Antonio, Almeida and Nunes, 2019](https://www.sciencedirect.com/science/article/pii/S2352340918315191).

Each observation represents a hotel booking due to arrive between the 1st of July of 2015 and the 31st of August 2017, including bookings that effectively arrived and bookings that were canceled. Since this is real hotel data, all data elements pertaining to hotel or customer identification were deleted.

### Variables: `hotels.csv`

|variable                         |class     |description |
|:--------------------------------|:---------|:-----------|
|`hotel`                          |character | Type of hotel (Resort Hotel or City Hotel)|
|`arrival_date`                   |double    | Arrival date reserved by the booking|
|`is_canceled`                    |double    | Value indicating if the booking was canceled (1) or not (0) |
|`lead_time`                      |double    | Number of days before the arrival date that the booking was reserved  |
|`stays_in_weekend_nights`        |double    | Number of weekend nights (Saturday or Sunday) the guest stayed or booked to stay at the hotel |
|`stays_in_week_nights`           |double    |Number of week nights (Monday to Friday) the guest stayed or booked to stay at the hotel|
|`adults`                         |double    | Number of adults who will stay|
|`children`                       |double    | Number of children who will stay|
|`babies`                         |double    | Number of babies who will stay|
|`meal`                           |character | Type of meal booked. Categories are presented in standard hospitality meal packages: <br> Undefined/SC – no meal package;<br>BB – Bed & Breakfast; <br> HB – Half board (breakfast and one other meal – usually dinner); <br> FB – Full board (breakfast, lunch and dinner) |
|`country`                        |character | Country of origin. Categories are represented in the ISO 3155–3:2013 format |
|`market_segment`                 |character | Booking market segment designation. In categories, the term "TA" means "Travel Agents" and "TO" means "Tour Operators" |
|`distribution_channel`           |character | Booking distribution channel. The term "TA" means "Travel Agents" and "TO" means "Tour Operators" |
|`is_repeated_guest`              |double    | Value indicating if the booking name was from a repeated guest (1) or not (0) |
|`previous_cancellations`         |double    | Number of previous bookings that were cancelled by the customer prior to the current booking |
|`previous_bookings_not_canceled` |double    | Number of previous bookings not cancelled by the customer prior to the current booking |
|`reserved_room_type`             |character | Code of room type reserved. Code is presented instead of designation for anonymity reasons |
|`assigned_room_type`             |character | Code for the type of room assigned to the booking. Sometimes the assigned room type differs from the reserved room type due to hotel operation reasons (e.g. overbooking) or by customer request. Code is presented instead of designation for anonymity reasons |
|`booking_changes`                |double    | Number of changes/amendments made to the booking from the moment the booking was entered on the PMS until the moment of check-in or cancellation|
|`deposit_type`                   |character | Indication on if the customer made a deposit to guarantee the booking. This variable can assume three categories:<br>No Deposit – no deposit was made;<br>Non Refund – a deposit was made in the value of the total stay cost;<br>Refundable – a deposit was made with a value under the total cost of stay. |
|`agent`                          |character | ID of the travel agency that made the booking |
|`company`                        |character | ID of the company/entity that made the booking or responsible for paying the booking. ID is presented instead of designation for anonymity reasons |
|`days_in_waiting_list`           |double    | Number of days the booking was in the waiting list before it was confirmed to the customer |
|`customer_type`                  |character | Type of booking, assuming one of four categories:<br>Contract – when the booking has an allotment or other type of contract associated to it;<br>Group – when the booking is associated to a group;<br>Transient – when the booking is not part of a group or contract, and is not associated to other transient booking;<br>Transient-party – when the booking is transient, but is associated to at least other transient booking|
|`adr`                            |double    | Average Daily Rate as defined by dividing the sum of all lodging transactions by the total number of staying nights |
|`required_car_parking_spaces`    |double    | Number of car parking spaces required by the customer |
|`total_of_special_requests`      |double    | Number of special requests made by the customer (e.g. twin bed or high floor)|
|`reservation_status`             |character | Reservation last status, assuming one of three categories:<br>Canceled – booking was canceled by the customer;<br>Check-Out – customer has checked in but already departed;<br>No-Show – customer did not check-in and did inform the hotel of the reason why |
|`reservation_status_date`        |double    | Date at which the last status was set. This variable can be used in conjunction with the `reservation_status` to understand when was the booking canceled or when the customer checked-out of the hotel. |
